<?php
// This script and data application were generated by AppGini 5.73
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");

	handle_maintenance();

	header('Content-type: text/javascript; charset=' . datalist_db_encoding);

	$table_perms = getTablePermissions('item');
	if(!$table_perms[0]){ die('// Access denied!'); }

	$mfk = $_GET['mfk'];
	$id = makeSafe($_GET['id']);
	$rnd1 = intval($_GET['rnd1']); if(!$rnd1) $rnd1 = '';

	if(!$mfk){
		die('// No js code available!');
	}

	switch($mfk){

		case 'colecao':
			if(!$id){
				?>
				$j('#colecao_codigo<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `colecao`.`id` as 'id', `colecao`.`colecao` as 'colecao', `colecao`.`codigo_colecao` as 'codigo_colecao' FROM `colecao`  WHERE `colecao`.`id`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#colecao_codigo<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['codigo_colecao']))); ?>&nbsp;');
			<?php
			break;

		case 'grupo':
			if(!$id){
				?>
				$j('#grupo_codigo<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `grupo`.`id` as 'id', IF(    CHAR_LENGTH(`colecao1`.`colecao`), CONCAT_WS('',   `colecao1`.`colecao`), '') as 'colecao', `grupo`.`grupo` as 'grupo', `grupo`.`codigo_grupo` as 'codigo_grupo' FROM `grupo` LEFT JOIN `colecao` as colecao1 ON `colecao1`.`id`=`grupo`.`colecao`  WHERE `grupo`.`id`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#grupo_codigo<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['codigo_grupo']))); ?>&nbsp;');
			<?php
			break;

		case 'serie':
			if(!$id){
				?>
				$j('#serie_codigo<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `serie`.`id` as 'id', IF(    CHAR_LENGTH(`grupo1`.`grupo`), CONCAT_WS('',   `grupo1`.`grupo`), '') as 'grupo', `serie`.`serie` as 'serie', `serie`.`codigo` as 'codigo' FROM `serie` LEFT JOIN `grupo` as grupo1 ON `grupo1`.`id`=`serie`.`grupo`  WHERE `serie`.`id`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#serie_codigo<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['codigo']))); ?>&nbsp;');
			<?php
			break;


	}

?>