<?php
// This script and data application were generated by AppGini 5.73
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/item.php");
	include("$currDir/item_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('item');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "item";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`item`.`id`" => "id",
		"`item`.`titulo`" => "titulo",
		"concat('<i class=\"glyphicon glyphicon-', if(`item`.`titulo_atribuido`, 'check', 'unchecked'), '\"></i>')" => "titulo_atribuido",
		"`item`.`descricao`" => "descricao",
		"if(`item`.`date`,date_format(`item`.`date`,'%d/%m/%Y'),'')" => "date",
		"`item`.`data_livre`" => "data_livre",
		"concat('<i class=\"glyphicon glyphicon-', if(`item`.`data_atribuida`, 'check', 'unchecked'), '\"></i>')" => "data_atribuida",
		"`item`.`autoria`" => "autoria",
		"`item`.`quantidade`" => "quantidade",
		"IF(    CHAR_LENGTH(`idioma1`.`idioma`), CONCAT_WS('',   `idioma1`.`idioma`), '') /* Idioma: */" => "idioma",
		"`item`.`local_producao`" => "local_producao",
		"IF(    CHAR_LENGTH(`local_comunicacao1`.`local_comunicacao`), CONCAT_WS('',   `local_comunicacao1`.`local_comunicacao`), '') /* Ve&#237;culo de Publica&#231;&#227;o: */" => "local_publicacao_veiculo",
		"`item`.`local_publicacao`" => "local_publicacao",
		"IF(    CHAR_LENGTH(`tipo_publicacao1`.`tipo_publicacao`), CONCAT_WS('',   `tipo_publicacao1`.`tipo_publicacao`), '') /* Tipo de Publica&#231;&#227;o: */" => "tipo_publicacao",
		"`item`.`identificacao`" => "identificacao",
		"IF(    CHAR_LENGTH(`colecao1`.`colecao`), CONCAT_WS('',   `colecao1`.`colecao`), '') /* Cole&#231;&#227;o: */" => "colecao",
		"IF(    CHAR_LENGTH(`colecao1`.`codigo_colecao`), CONCAT_WS('',   `colecao1`.`codigo_colecao`), '') /* C&#243;digo da Cole&#231;&#227;o: */" => "colecao_codigo",
		"IF(    CHAR_LENGTH(`grupo1`.`grupo`), CONCAT_WS('',   `grupo1`.`grupo`), '') /* Grupo: */" => "grupo",
		"IF(    CHAR_LENGTH(`grupo1`.`codigo_grupo`), CONCAT_WS('',   `grupo1`.`codigo_grupo`), '') /* C&#243;digo do Grupo: */" => "grupo_codigo",
		"IF(    CHAR_LENGTH(`serie1`.`serie`), CONCAT_WS('',   `serie1`.`serie`), '') /* S&#233;rie: */" => "serie",
		"IF(    CHAR_LENGTH(`serie1`.`codigo`), CONCAT_WS('',   `serie1`.`codigo`), '') /* C&#243;digo da S&#233;rie: */" => "serie_codigo",
		"IF(    CHAR_LENGTH(`subserie1`.`subserie`), CONCAT_WS('',   `subserie1`.`subserie`), '') /* Subs&#233;rie: */" => "subserie",
		"`item`.`numero_serie`" => "numero_serie",
		"IF(    CHAR_LENGTH(`tipologia1`.`tipologia`), CONCAT_WS('',   `tipologia1`.`tipologia`), '') /* Tipologia / Esp&#233;cie: */" => "tipologia",
		"IF(    CHAR_LENGTH(`genero1`.`genero`), CONCAT_WS('',   `genero1`.`genero`), '') /* G&#234;nero: */" => "genero",
		"`item`.`forma`" => "forma",
		"IF(    CHAR_LENGTH(`formato1`.`formato`), CONCAT_WS('',   `formato1`.`formato`), '') /* Formato: */" => "formato",
		"`item`.`escritura`" => "escritura",
		"IF(    CHAR_LENGTH(`suporte1`.`suporte`), CONCAT_WS('',   `suporte1`.`suporte`), '') /* Suporte: */" => "suporte",
		"`item`.`dimensao`" => "dimensao",
		"`item`.`estado_conservacao`" => "estado_conservacao",
		"`item`.`observacoes`" => "observacoes",
		"IF(    CHAR_LENGTH(`item1`.`identificacao`) || CHAR_LENGTH(`item1`.`titulo`), CONCAT_WS('',   `item1`.`identificacao`, ' - ', `item1`.`titulo`), '') /* Documentos Relacionados: */" => "documentos_relacionados",
		"IF(    CHAR_LENGTH(`numero_caixa1`.`numero_caixa`), CONCAT_WS('',   `numero_caixa1`.`numero_caixa`), '') /* N&#250;mero da Caixa: */" => "numero_caixa",
		"IF(    CHAR_LENGTH(`nome_caixa1`.`nome_caixa`), CONCAT_WS('',   `nome_caixa1`.`nome_caixa`), '') /* Nome da Caixa: */" => "nome_caixa",
		"IF(    CHAR_LENGTH(`numero_pasta1`.`numero_pasta`), CONCAT_WS('',   `numero_pasta1`.`numero_pasta`), '') /* N&#250;mero da Pasta: */" => "numero_pasta",
		"IF(    CHAR_LENGTH(`nome_pasta1`.`nome_pasta`), CONCAT_WS('',   `nome_pasta1`.`nome_pasta`), '') /* Nome da pasta: */" => "nome_pasta",
		"`item`.`upload`" => "upload",
		"`item`.`usuario_cadastro`" => "usuario_cadastro",
		"`item`.`usuario_alteracao`" => "usuario_alteracao",
		"concat('<i class=\"glyphicon glyphicon-', if(`item`.`publicar`, 'check', 'unchecked'), '\"></i>')" => "publicar"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`item`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => '`item`.`date`',
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => '`idioma1`.`idioma`',
		11 => 11,
		12 => '`local_comunicacao1`.`local_comunicacao`',
		13 => 13,
		14 => '`tipo_publicacao1`.`tipo_publicacao`',
		15 => 15,
		16 => '`colecao1`.`colecao`',
		17 => '`colecao1`.`codigo_colecao`',
		18 => '`grupo1`.`grupo`',
		19 => '`grupo1`.`codigo_grupo`',
		20 => '`serie1`.`serie`',
		21 => '`serie1`.`codigo`',
		22 => '`subserie1`.`subserie`',
		23 => '`item`.`numero_serie`',
		24 => '`tipologia1`.`tipologia`',
		25 => '`genero1`.`genero`',
		26 => 26,
		27 => '`formato1`.`formato`',
		28 => 28,
		29 => '`suporte1`.`suporte`',
		30 => 30,
		31 => 31,
		32 => 32,
		33 => 33,
		34 => '`numero_caixa1`.`numero_caixa`',
		35 => '`nome_caixa1`.`nome_caixa`',
		36 => '`numero_pasta1`.`numero_pasta`',
		37 => '`nome_pasta1`.`nome_pasta`',
		38 => 38,
		39 => 39,
		40 => 40,
		41 => 41
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`item`.`id`" => "id",
		"`item`.`titulo`" => "titulo",
		"`item`.`titulo_atribuido`" => "titulo_atribuido",
		"`item`.`descricao`" => "descricao",
		"if(`item`.`date`,date_format(`item`.`date`,'%d/%m/%Y'),'')" => "date",
		"`item`.`data_livre`" => "data_livre",
		"`item`.`data_atribuida`" => "data_atribuida",
		"`item`.`autoria`" => "autoria",
		"`item`.`quantidade`" => "quantidade",
		"IF(    CHAR_LENGTH(`idioma1`.`idioma`), CONCAT_WS('',   `idioma1`.`idioma`), '') /* Idioma: */" => "idioma",
		"`item`.`local_producao`" => "local_producao",
		"IF(    CHAR_LENGTH(`local_comunicacao1`.`local_comunicacao`), CONCAT_WS('',   `local_comunicacao1`.`local_comunicacao`), '') /* Ve&#237;culo de Publica&#231;&#227;o: */" => "local_publicacao_veiculo",
		"`item`.`local_publicacao`" => "local_publicacao",
		"IF(    CHAR_LENGTH(`tipo_publicacao1`.`tipo_publicacao`), CONCAT_WS('',   `tipo_publicacao1`.`tipo_publicacao`), '') /* Tipo de Publica&#231;&#227;o: */" => "tipo_publicacao",
		"`item`.`identificacao`" => "identificacao",
		"IF(    CHAR_LENGTH(`colecao1`.`colecao`), CONCAT_WS('',   `colecao1`.`colecao`), '') /* Cole&#231;&#227;o: */" => "colecao",
		"IF(    CHAR_LENGTH(`colecao1`.`codigo_colecao`), CONCAT_WS('',   `colecao1`.`codigo_colecao`), '') /* C&#243;digo da Cole&#231;&#227;o: */" => "colecao_codigo",
		"IF(    CHAR_LENGTH(`grupo1`.`grupo`), CONCAT_WS('',   `grupo1`.`grupo`), '') /* Grupo: */" => "grupo",
		"IF(    CHAR_LENGTH(`grupo1`.`codigo_grupo`), CONCAT_WS('',   `grupo1`.`codigo_grupo`), '') /* C&#243;digo do Grupo: */" => "grupo_codigo",
		"IF(    CHAR_LENGTH(`serie1`.`serie`), CONCAT_WS('',   `serie1`.`serie`), '') /* S&#233;rie: */" => "serie",
		"IF(    CHAR_LENGTH(`serie1`.`codigo`), CONCAT_WS('',   `serie1`.`codigo`), '') /* C&#243;digo da S&#233;rie: */" => "serie_codigo",
		"IF(    CHAR_LENGTH(`subserie1`.`subserie`), CONCAT_WS('',   `subserie1`.`subserie`), '') /* Subs&#233;rie: */" => "subserie",
		"`item`.`numero_serie`" => "numero_serie",
		"IF(    CHAR_LENGTH(`tipologia1`.`tipologia`), CONCAT_WS('',   `tipologia1`.`tipologia`), '') /* Tipologia / Esp&#233;cie: */" => "tipologia",
		"IF(    CHAR_LENGTH(`genero1`.`genero`), CONCAT_WS('',   `genero1`.`genero`), '') /* G&#234;nero: */" => "genero",
		"`item`.`forma`" => "forma",
		"IF(    CHAR_LENGTH(`formato1`.`formato`), CONCAT_WS('',   `formato1`.`formato`), '') /* Formato: */" => "formato",
		"`item`.`escritura`" => "escritura",
		"IF(    CHAR_LENGTH(`suporte1`.`suporte`), CONCAT_WS('',   `suporte1`.`suporte`), '') /* Suporte: */" => "suporte",
		"`item`.`dimensao`" => "dimensao",
		"`item`.`estado_conservacao`" => "estado_conservacao",
		"`item`.`observacoes`" => "observacoes",
		"IF(    CHAR_LENGTH(`item1`.`identificacao`) || CHAR_LENGTH(`item1`.`titulo`), CONCAT_WS('',   `item1`.`identificacao`, ' - ', `item1`.`titulo`), '') /* Documentos Relacionados: */" => "documentos_relacionados",
		"IF(    CHAR_LENGTH(`numero_caixa1`.`numero_caixa`), CONCAT_WS('',   `numero_caixa1`.`numero_caixa`), '') /* N&#250;mero da Caixa: */" => "numero_caixa",
		"IF(    CHAR_LENGTH(`nome_caixa1`.`nome_caixa`), CONCAT_WS('',   `nome_caixa1`.`nome_caixa`), '') /* Nome da Caixa: */" => "nome_caixa",
		"IF(    CHAR_LENGTH(`numero_pasta1`.`numero_pasta`), CONCAT_WS('',   `numero_pasta1`.`numero_pasta`), '') /* N&#250;mero da Pasta: */" => "numero_pasta",
		"IF(    CHAR_LENGTH(`nome_pasta1`.`nome_pasta`), CONCAT_WS('',   `nome_pasta1`.`nome_pasta`), '') /* Nome da pasta: */" => "nome_pasta",
		"`item`.`upload`" => "upload",
		"`item`.`usuario_cadastro`" => "usuario_cadastro",
		"`item`.`usuario_alteracao`" => "usuario_alteracao",
		"`item`.`publicar`" => "publicar"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`item`.`id`" => "ID",
		"`item`.`titulo`" => "T&#237;tulo:",
		"`item`.`titulo_atribuido`" => "T&#237;tulo Atribu&#237;do",
		"`item`.`descricao`" => "Descri&#231;&#227;o:",
		"`item`.`date`" => "Data:",
		"`item`.`data_livre`" => "Data / Per&#237;odo:",
		"`item`.`data_atribuida`" => "Data Atribu&#237;da",
		"`item`.`autoria`" => "Autoria:",
		"`item`.`quantidade`" => "Quantidade:",
		"IF(    CHAR_LENGTH(`idioma1`.`idioma`), CONCAT_WS('',   `idioma1`.`idioma`), '') /* Idioma: */" => "Idioma:",
		"`item`.`local_producao`" => "Local de Produ&#231;&#227;o:",
		"IF(    CHAR_LENGTH(`local_comunicacao1`.`local_comunicacao`), CONCAT_WS('',   `local_comunicacao1`.`local_comunicacao`), '') /* Ve&#237;culo de Publica&#231;&#227;o: */" => "Ve&#237;culo de Publica&#231;&#227;o:",
		"`item`.`local_publicacao`" => "Local de Publica&#231;&#227;o:",
		"IF(    CHAR_LENGTH(`tipo_publicacao1`.`tipo_publicacao`), CONCAT_WS('',   `tipo_publicacao1`.`tipo_publicacao`), '') /* Tipo de Publica&#231;&#227;o: */" => "Tipo de Publica&#231;&#227;o:",
		"`item`.`identificacao`" => "Identifica&#231;&#227;o:",
		"IF(    CHAR_LENGTH(`colecao1`.`colecao`), CONCAT_WS('',   `colecao1`.`colecao`), '') /* Cole&#231;&#227;o: */" => "Cole&#231;&#227;o:",
		"IF(    CHAR_LENGTH(`colecao1`.`codigo_colecao`), CONCAT_WS('',   `colecao1`.`codigo_colecao`), '') /* C&#243;digo da Cole&#231;&#227;o: */" => "C&#243;digo da Cole&#231;&#227;o:",
		"IF(    CHAR_LENGTH(`grupo1`.`grupo`), CONCAT_WS('',   `grupo1`.`grupo`), '') /* Grupo: */" => "Grupo:",
		"IF(    CHAR_LENGTH(`grupo1`.`codigo_grupo`), CONCAT_WS('',   `grupo1`.`codigo_grupo`), '') /* C&#243;digo do Grupo: */" => "C&#243;digo do Grupo:",
		"IF(    CHAR_LENGTH(`serie1`.`serie`), CONCAT_WS('',   `serie1`.`serie`), '') /* S&#233;rie: */" => "S&#233;rie:",
		"IF(    CHAR_LENGTH(`serie1`.`codigo`), CONCAT_WS('',   `serie1`.`codigo`), '') /* C&#243;digo da S&#233;rie: */" => "C&#243;digo da S&#233;rie:",
		"IF(    CHAR_LENGTH(`subserie1`.`subserie`), CONCAT_WS('',   `subserie1`.`subserie`), '') /* Subs&#233;rie: */" => "Subs&#233;rie:",
		"`item`.`numero_serie`" => "N&#250;mero S&#233;rie",
		"IF(    CHAR_LENGTH(`tipologia1`.`tipologia`), CONCAT_WS('',   `tipologia1`.`tipologia`), '') /* Tipologia / Esp&#233;cie: */" => "Tipologia / Esp&#233;cie:",
		"IF(    CHAR_LENGTH(`genero1`.`genero`), CONCAT_WS('',   `genero1`.`genero`), '') /* G&#234;nero: */" => "G&#234;nero:",
		"`item`.`forma`" => "Forma:",
		"IF(    CHAR_LENGTH(`formato1`.`formato`), CONCAT_WS('',   `formato1`.`formato`), '') /* Formato: */" => "Formato:",
		"`item`.`escritura`" => "Escritura:",
		"IF(    CHAR_LENGTH(`suporte1`.`suporte`), CONCAT_WS('',   `suporte1`.`suporte`), '') /* Suporte: */" => "Suporte:",
		"`item`.`dimensao`" => "Dimens&#227;o:",
		"`item`.`estado_conservacao`" => "Estado de Conserva&#231;&#227;o:",
		"`item`.`observacoes`" => "Observa&#231;&#245;es:",
		"IF(    CHAR_LENGTH(`item1`.`identificacao`) || CHAR_LENGTH(`item1`.`titulo`), CONCAT_WS('',   `item1`.`identificacao`, ' - ', `item1`.`titulo`), '') /* Documentos Relacionados: */" => "Documentos Relacionados:",
		"IF(    CHAR_LENGTH(`numero_caixa1`.`numero_caixa`), CONCAT_WS('',   `numero_caixa1`.`numero_caixa`), '') /* N&#250;mero da Caixa: */" => "N&#250;mero da Caixa:",
		"IF(    CHAR_LENGTH(`nome_caixa1`.`nome_caixa`), CONCAT_WS('',   `nome_caixa1`.`nome_caixa`), '') /* Nome da Caixa: */" => "Nome da Caixa:",
		"IF(    CHAR_LENGTH(`numero_pasta1`.`numero_pasta`), CONCAT_WS('',   `numero_pasta1`.`numero_pasta`), '') /* N&#250;mero da Pasta: */" => "N&#250;mero da Pasta:",
		"IF(    CHAR_LENGTH(`nome_pasta1`.`nome_pasta`), CONCAT_WS('',   `nome_pasta1`.`nome_pasta`), '') /* Nome da pasta: */" => "Nome da pasta:",
		"`item`.`upload`" => "Upload",
		"`item`.`usuario_cadastro`" => "Cadastro feito pelo usu&#225;rio:",
		"`item`.`usuario_alteracao`" => "&#218;ltima edi&#231;&#227;o feita pelo usu&#225;rio:",
		"`item`.`publicar`" => "Publicar"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`item`.`id`" => "id",
		"`item`.`titulo`" => "titulo",
		"concat('<i class=\"glyphicon glyphicon-', if(`item`.`titulo_atribuido`, 'check', 'unchecked'), '\"></i>')" => "titulo_atribuido",
		"`item`.`descricao`" => "descricao",
		"if(`item`.`date`,date_format(`item`.`date`,'%d/%m/%Y'),'')" => "date",
		"`item`.`data_livre`" => "data_livre",
		"concat('<i class=\"glyphicon glyphicon-', if(`item`.`data_atribuida`, 'check', 'unchecked'), '\"></i>')" => "data_atribuida",
		"`item`.`autoria`" => "autoria",
		"`item`.`quantidade`" => "quantidade",
		"IF(    CHAR_LENGTH(`idioma1`.`idioma`), CONCAT_WS('',   `idioma1`.`idioma`), '') /* Idioma: */" => "idioma",
		"`item`.`local_producao`" => "local_producao",
		"IF(    CHAR_LENGTH(`local_comunicacao1`.`local_comunicacao`), CONCAT_WS('',   `local_comunicacao1`.`local_comunicacao`), '') /* Ve&#237;culo de Publica&#231;&#227;o: */" => "local_publicacao_veiculo",
		"`item`.`local_publicacao`" => "local_publicacao",
		"IF(    CHAR_LENGTH(`tipo_publicacao1`.`tipo_publicacao`), CONCAT_WS('',   `tipo_publicacao1`.`tipo_publicacao`), '') /* Tipo de Publica&#231;&#227;o: */" => "tipo_publicacao",
		"`item`.`identificacao`" => "identificacao",
		"IF(    CHAR_LENGTH(`colecao1`.`colecao`), CONCAT_WS('',   `colecao1`.`colecao`), '') /* Cole&#231;&#227;o: */" => "colecao",
		"IF(    CHAR_LENGTH(`colecao1`.`codigo_colecao`), CONCAT_WS('',   `colecao1`.`codigo_colecao`), '') /* C&#243;digo da Cole&#231;&#227;o: */" => "colecao_codigo",
		"IF(    CHAR_LENGTH(`grupo1`.`grupo`), CONCAT_WS('',   `grupo1`.`grupo`), '') /* Grupo: */" => "grupo",
		"IF(    CHAR_LENGTH(`grupo1`.`codigo_grupo`), CONCAT_WS('',   `grupo1`.`codigo_grupo`), '') /* C&#243;digo do Grupo: */" => "grupo_codigo",
		"IF(    CHAR_LENGTH(`serie1`.`serie`), CONCAT_WS('',   `serie1`.`serie`), '') /* S&#233;rie: */" => "serie",
		"IF(    CHAR_LENGTH(`serie1`.`codigo`), CONCAT_WS('',   `serie1`.`codigo`), '') /* C&#243;digo da S&#233;rie: */" => "serie_codigo",
		"IF(    CHAR_LENGTH(`subserie1`.`subserie`), CONCAT_WS('',   `subserie1`.`subserie`), '') /* Subs&#233;rie: */" => "subserie",
		"`item`.`numero_serie`" => "numero_serie",
		"IF(    CHAR_LENGTH(`tipologia1`.`tipologia`), CONCAT_WS('',   `tipologia1`.`tipologia`), '') /* Tipologia / Esp&#233;cie: */" => "tipologia",
		"IF(    CHAR_LENGTH(`genero1`.`genero`), CONCAT_WS('',   `genero1`.`genero`), '') /* G&#234;nero: */" => "genero",
		"`item`.`forma`" => "forma",
		"IF(    CHAR_LENGTH(`formato1`.`formato`), CONCAT_WS('',   `formato1`.`formato`), '') /* Formato: */" => "formato",
		"`item`.`escritura`" => "escritura",
		"IF(    CHAR_LENGTH(`suporte1`.`suporte`), CONCAT_WS('',   `suporte1`.`suporte`), '') /* Suporte: */" => "suporte",
		"`item`.`dimensao`" => "dimensao",
		"`item`.`estado_conservacao`" => "estado_conservacao",
		"`item`.`observacoes`" => "observacoes",
		"IF(    CHAR_LENGTH(`item1`.`identificacao`) || CHAR_LENGTH(`item1`.`titulo`), CONCAT_WS('',   `item1`.`identificacao`, ' - ', `item1`.`titulo`), '') /* Documentos Relacionados: */" => "documentos_relacionados",
		"IF(    CHAR_LENGTH(`numero_caixa1`.`numero_caixa`), CONCAT_WS('',   `numero_caixa1`.`numero_caixa`), '') /* N&#250;mero da Caixa: */" => "numero_caixa",
		"IF(    CHAR_LENGTH(`nome_caixa1`.`nome_caixa`), CONCAT_WS('',   `nome_caixa1`.`nome_caixa`), '') /* Nome da Caixa: */" => "nome_caixa",
		"IF(    CHAR_LENGTH(`numero_pasta1`.`numero_pasta`), CONCAT_WS('',   `numero_pasta1`.`numero_pasta`), '') /* N&#250;mero da Pasta: */" => "numero_pasta",
		"IF(    CHAR_LENGTH(`nome_pasta1`.`nome_pasta`), CONCAT_WS('',   `nome_pasta1`.`nome_pasta`), '') /* Nome da pasta: */" => "nome_pasta",
		"`item`.`upload`" => "upload",
		"`item`.`usuario_cadastro`" => "usuario_cadastro",
		"`item`.`usuario_alteracao`" => "usuario_alteracao",
		"concat('<i class=\"glyphicon glyphicon-', if(`item`.`publicar`, 'check', 'unchecked'), '\"></i>')" => "publicar"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'idioma' => 'Idioma:', 'local_publicacao_veiculo' => 'Ve&#237;culo de Publica&#231;&#227;o:', 'tipo_publicacao' => 'Tipo de Publica&#231;&#227;o:', 'colecao' => 'Cole&#231;&#227;o:', 'grupo' => 'Grupo:', 'serie' => 'S&#233;rie:', 'subserie' => 'Subs&#233;rie:', 'tipologia' => 'Tipologia / Esp&#233;cie:', 'genero' => 'G&#234;nero:', 'formato' => 'Formato:', 'suporte' => 'Suporte:', 'documentos_relacionados' => 'Documentos Relacionados:', 'numero_caixa' => 'N&#250;mero da Caixa:', 'nome_caixa' => 'Nome da Caixa:', 'numero_pasta' => 'N&#250;mero da Pasta:', 'nome_pasta' => 'Nome da pasta:');

	$x->QueryFrom = "`item` LEFT JOIN `idioma` as idioma1 ON `idioma1`.`id`=`item`.`idioma` LEFT JOIN `local_comunicacao` as local_comunicacao1 ON `local_comunicacao1`.`id`=`item`.`local_publicacao_veiculo` LEFT JOIN `tipo_publicacao` as tipo_publicacao1 ON `tipo_publicacao1`.`id`=`item`.`tipo_publicacao` LEFT JOIN `colecao` as colecao1 ON `colecao1`.`id`=`item`.`colecao` LEFT JOIN `grupo` as grupo1 ON `grupo1`.`id`=`item`.`grupo` LEFT JOIN `serie` as serie1 ON `serie1`.`id`=`item`.`serie` LEFT JOIN `subserie` as subserie1 ON `subserie1`.`id`=`item`.`subserie` LEFT JOIN `tipologia` as tipologia1 ON `tipologia1`.`id`=`item`.`tipologia` LEFT JOIN `genero` as genero1 ON `genero1`.`id`=`item`.`genero` LEFT JOIN `formato` as formato1 ON `formato1`.`id`=`item`.`formato` LEFT JOIN `suporte` as suporte1 ON `suporte1`.`id`=`item`.`suporte` LEFT JOIN `item` as item1 ON `item1`.`id`=`item`.`documentos_relacionados` LEFT JOIN `numero_caixa` as numero_caixa1 ON `numero_caixa1`.`id`=`item`.`numero_caixa` LEFT JOIN `nome_caixa` as nome_caixa1 ON `nome_caixa1`.`id`=`item`.`nome_caixa` LEFT JOIN `numero_pasta` as numero_pasta1 ON `numero_pasta1`.`id`=`item`.`numero_pasta` LEFT JOIN `nome_pasta` as nome_pasta1 ON `nome_pasta1`.`id`=`item`.`nome_pasta` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 25;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "item_view.php";
	$x->RedirectAfterInsert = "item_view.php?addNew_x=1";
	$x->TableTitle = "Itens";
	$x->TableIcon = "resources/table_icons/curriculum_vitae.png";
	$x->PrimaryKey = "`item`.`id`";
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("T&#237;tulo:", "T&#237;tulo Atribu&#237;do", "Descri&#231;&#227;o:", "Data:", "Data / Per&#237;odo:", "Data Atribu&#237;da", "Autoria:", "Quantidade:", "Idioma:", "Local de Produ&#231;&#227;o:", "Ve&#237;culo de Publica&#231;&#227;o:", "Local de Publica&#231;&#227;o:", "Tipo de Publica&#231;&#227;o:", "Identifica&#231;&#227;o:", "Cole&#231;&#227;o:", "C&#243;digo da Cole&#231;&#227;o:", "Grupo:", "C&#243;digo do Grupo:", "S&#233;rie:", "C&#243;digo da S&#233;rie:", "Subs&#233;rie:", "Tipologia / Esp&#233;cie:", "G&#234;nero:", "Forma:", "Formato:", "Escritura:", "Suporte:", "Dimens&#227;o:", "Estado de Conserva&#231;&#227;o:", "Observa&#231;&#245;es:", "Documentos Relacionados:", "N&#250;mero da Caixa:", "Nome da Caixa:", "N&#250;mero da Pasta:", "Nome da pasta:", "Upload", "Publicar");
	$x->ColFieldName = array('titulo', 'titulo_atribuido', 'descricao', 'date', 'data_livre', 'data_atribuida', 'autoria', 'quantidade', 'idioma', 'local_producao', 'local_publicacao_veiculo', 'local_publicacao', 'tipo_publicacao', 'identificacao', 'colecao', 'colecao_codigo', 'grupo', 'grupo_codigo', 'serie', 'serie_codigo', 'subserie', 'tipologia', 'genero', 'forma', 'formato', 'escritura', 'suporte', 'dimensao', 'estado_conservacao', 'observacoes', 'documentos_relacionados', 'numero_caixa', 'nome_caixa', 'numero_pasta', 'nome_pasta', 'upload', 'publicar');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 41);

	// template paths below are based on the app main directory
	$x->Template = 'templates/item_templateTV.html';
	$x->SelectedTemplate = 'templates/item_templateTVS.html';
	$x->TemplateDV = 'templates/item_templateDV.html';
	$x->TemplateDVP = 'templates/item_templateDVP.html';

	$x->ShowTableHeader = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `item`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='item' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `item`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='item' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`item`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: item_init
	$render=TRUE;
	if(function_exists('item_init')){
		$args=array();
		$render=item_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: item_header
	$headerCode='';
	if(function_exists('item_header')){
		$args=array();
		$headerCode=item_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: item_footer
	$footerCode='';
	if(function_exists('item_footer')){
		$args=array();
		$footerCode=item_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>