<?php
// This script and data application were generated by AppGini 5.73
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/subserie.php");
	include("$currDir/subserie_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('subserie');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "subserie";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`subserie`.`id`" => "id",
		"IF(    CHAR_LENGTH(`serie1`.`serie`), CONCAT_WS('',   `serie1`.`serie`), '') /* S&#233;rie: */" => "serie",
		"`subserie`.`subserie`" => "subserie"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`subserie`.`id`',
		2 => '`serie1`.`serie`',
		3 => 3
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`subserie`.`id`" => "id",
		"IF(    CHAR_LENGTH(`serie1`.`serie`), CONCAT_WS('',   `serie1`.`serie`), '') /* S&#233;rie: */" => "serie",
		"`subserie`.`subserie`" => "subserie"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`subserie`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`serie1`.`serie`), CONCAT_WS('',   `serie1`.`serie`), '') /* S&#233;rie: */" => "S&#233;rie:",
		"`subserie`.`subserie`" => "Subs&#233;rie:"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`subserie`.`id`" => "id",
		"IF(    CHAR_LENGTH(`serie1`.`serie`), CONCAT_WS('',   `serie1`.`serie`), '') /* S&#233;rie: */" => "serie",
		"`subserie`.`subserie`" => "subserie"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'serie' => 'S&#233;rie:');

	$x->QueryFrom = "`subserie` LEFT JOIN `serie` as serie1 ON `serie1`.`id`=`subserie`.`serie` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 15;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "subserie_view.php";
	$x->RedirectAfterInsert = "subserie_view.php?addNew_x=1";
	$x->TableTitle = "Subs&#233;rie";
	$x->TableIcon = "resources/table_icons/document_copies.png";
	$x->PrimaryKey = "`subserie`.`id`";
	$x->DefaultSortField = '3';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  150, 150);
	$x->ColCaption = array("S&#233;rie:", "Subs&#233;rie:");
	$x->ColFieldName = array('serie', 'subserie');
	$x->ColNumber  = array(2, 3);

	// template paths below are based on the app main directory
	$x->Template = 'templates/subserie_templateTV.html';
	$x->SelectedTemplate = 'templates/subserie_templateTVS.html';
	$x->TemplateDV = 'templates/subserie_templateDV.html';
	$x->TemplateDVP = 'templates/subserie_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `subserie`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='subserie' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `subserie`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='subserie' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`subserie`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: subserie_init
	$render=TRUE;
	if(function_exists('subserie_init')){
		$args=array();
		$render=subserie_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: subserie_header
	$headerCode='';
	if(function_exists('subserie_header')){
		$args=array();
		$headerCode=subserie_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: subserie_footer
	$footerCode='';
	if(function_exists('subserie_footer')){
		$args=array();
		$footerCode=subserie_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>